name: Sync Fork
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 开始同步
        run: echo "开始同步本地仓库与上游仓库..."

      - name: Sync Upstream
        uses: aormsby/fork-sync-with-upstream-action@v3.4
        with:
          upstream_sync_repo: KuekHaoYang/KVideo
          upstream_sync_branch: main
          target_sync_branch: main
          upstream_repo_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: 检查更新
        run: echo "检查上游仓库是否有更新..."

      - name: 同步完成
        run: echo "同步完成。如果有新更新，已同步到本地仓库。"

      - name: 推送消息到 Telegram
        run: |
          SYNC_STATUS=$(git log origin/main..upstream/main --oneline)
          
          if [ -z "$SYNC_STATUS" ]; then
            MESSAGE='✅KVideo仓库提醒\nGitHub Action 同步操作完成。\n上游仓库没有新的更新，无需同步。'
          else
            MESSAGE='✅KVideo仓库提醒\nGitHub Action 同步操作完成。\n上游仓库有新更新，已成功同步到本地仓库。'
          fi

          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            --data-urlencode "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            --data-urlencode "text=${MESSAGE}" \
            --data-urlencode "parse_mode=HTML"
